export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCT",
  CART_PRODUCTS: "SET_CART_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
};
